#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

# picks up the dry run mode if provided
while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

log "$script_dir -- $filter"

cd $script_dir

# Always run brew first if it exists and no specific filter is provided
if [[ -z "$filter" && -x "./runs/brew" ]]; then
    execute ./runs/brew
fi

scripts=$(find ./runs -maxdepth 1 -mindepth 1 -type f -perm -0111 | grep -v "./runs/brew")

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "skip: $script"
        continue
    fi

    execute ./$script
done
