#!/usr/bin/env bash

brew install obsidian
brew install raycast
brew install flux
brew install karabiner-elements
brew install maestral
brew install docker
brew install zen-browser
brew install google-chrome
brew install bitwarden
brew install meetingbar
brew install logi-options+
brew install telegram
brew install signal
brew install yubico-yubikey-manager
brew install spotify
brew install vlc
