#!/usr/bin/env bash

brew install fish
brew install fisher
brew install eza

mkdir -p "$HOME/.config/fish"
cp ./config/fish/config.fish "$HOME/.config/fish/config.fish"

if [ ! -f "$HOME/.config/fish/secrets.fish" ]; then
    cp ./config/fish/secrets.fish.example "$HOME/.config/fish/secrets.fish"
fi

fish_path="$(command -v fish)"
if grep -qx "$fish_path" /etc/shells; then
    if [ "$SHELL" != "$fish_path" ]; then
        chsh -s "$fish_path"
    fi
else
    echo "Add $fish_path to /etc/shells before setting Fish as the default shell."
fi

fish -c "fisher install IlanCosman/tide@v6"
fish -c "fisher install jhillyerd/plugin-git"
fish -c "fisher install franciscolourenco/done"
fish -c "fisher install plttn/fish-eza"
fish -c "fisher install rstacruz/fish-asdf"
fish -c "fisher install jethrokuan/fzf"
