#!/usr/bin/env bash

brew install fish
brew install fisher
brew install eza


fish -c "fisher install IlanCosman/tide@v6"
fish -c "fisher install jhillyerd/plugin-git"
fish -c "fisher install jethrokuan/z"
fish -c "fisher install franciscolourenco/done"
fish -c "fisher install plttn/fish-eza"
fish -c "fisher install rstacruz/fish-asdf"
fish -c "fisher install jethrokuan/fzf"
