#!/usr/bin/env bash

root="projects"
scopes=("personal" "work")

for scope in "${scopes[@]}"; do
    echo "[$task]: create '$scope' folder in $HOME/$root"
    [ ! -d "$HOME/$root/$scope" ] && mkdir -p "$HOME/$root/$scope"
done
