#!/usr/bin/env bash

root="projects"
scopes=("personal" "work")

for scope in "${scopes[@]}"; do
    echo "[$task]: create '$scope' folder in $HOME/$root"
    [ ! -d "$HOME/$root/$scope" ] && mkdir -p "$HOME/$root/$scope"
done

DROPBOX_DIR="$HOME/dropbox"

if [ -d "$DROPBOX_DIR" ]; then
    echo "dropbox folder already exists at $DROPBOX_DIR"
else
    mkdir -p "$DROPBOX_DIR"
    echo "$DROPBOX_DIR folder created successfully"
fi
