#!/usr/bin/env bash

brew install git
git -v

cp ./dotfiles/.gitconfig-personal $HOME/.gitconfig-personal
cp ./dotfiles/.gitconfig-work $HOME/.gitconfig-work
cp ./dotfiles/.gitconfig $HOME/.gitconfig

cp ./dotfiles/.gitignore $HOME/.gitignore
git config --global core.excludefiles $HOME/.gitignore
