#!/usr/bin/env bash

brew install newsboat

mkdir -p "$HOME/.newsboat"

DROPBOX="$HOME/Dropbox/Apps/newsboat"

if [ -d "$DROPBOX" ]; then
    files=(config urls summarize.conf newsboat-summarize)
    for f in "${files[@]}"; do
        [ -f "$DROPBOX/$f" ] && cp "$DROPBOX/$f" "$HOME/.newsboat/$f" && echo "Restored: $f"
    done
else
    cp ./config/newsboat/config "$HOME/.newsboat/config"
    echo "No Dropbox backup found, copied config from dotfiles"
fi
