#!/usr/bin/env bash

# unix
brew install tldr
brew install xclip
brew install jq
brew install parallel
brew install htop

# rest
brew install zoxide
brew install fzf
brew install ripgrep
brew install tree

# brew install yarn
# brew install node asdf
