#!/usr/bin/env bash

# unix
brew install tldr
brew install xclip
brew install jq
brew install parallel
brew install bat
brew install fd
brew install ripgrep
brew install fzf
brew install tree
brew install lazygit

# rest
brew install zoxide
zoxide init --cmd cd fish | source

brew install gh
brew install the-unarchiver
brew install ffmpeg
brew install pass
