#!/usr/bin/env bash

brew install visual-studio-code

code --install-extension aaron-bond.better-comments
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension vscodevim.vim
code --install-extension vscode-icons-team.vscode-icons
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension yoavbls.pretty-ts-errors
code --install-extension catppuccin.catppuccin-vsc
code --install-extension monish.regexsnippets
code --install-extension arcanis.vscode-zipfs
code --install-extension tobias-z.vscode-harpoon

# MacOS specific
cp ./config/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
